config/routes.rb
Parse::Application.routes.draw do
  resources :parsings
  root to: 'parsings#index'

end

app/models/parsing.rb
class Parsing < ActiveRecord::Base
  attr_accessible :Page, :body, :link, :num, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/parsings_controller.rb
require 'nokogiri'         
require 'open-uri'

class ParsingsController < ApplicationController
  # GET /parsings
  # GET /parsings.json
  def index
    @parsings = Parsing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parsings }
    end
  end

  # GET /parsings/1
  # GET /parsings/1.json
  def show
    @parsing = Parsing.find(params[:id])

    @page = Nokogiri::HTML(open(@parsing.link))
    @number = @parsing.num.to_i
    i=0
    @string = ""
    @number.to_i.times do
        title = @page.css('div.item-list_info')[i].css('h4').text
        params =  @page.css('div.item-list_info')[i].css('ul').text.gsub(/\s+/, " ")
        price =  @page.css('div.item-list_info')[i].css('p.price').css('span.bold').text.gsub(/\s+/, "").to_i
        img = @page.css('div.photo_border_corners')[i].css('img')[0]
        @link_img = img['src']
        new_price = price - (price / 100 * 10)
        @string += "</br> #{title} #{params} #{new_price.to_s} p. <img src=' http://www.lepnina.ru/#{@link_img}'> </br>"
        #@string += "</br>" + title + params  + new_price.to_s + " p." + "<img src=' http://www.lepnina.ru/#{@link_img}'>" + "</br>"
        i+=1
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @parsing }
    end
  end

  # GET /parsings/new
  # GET /parsings/new.json
  def new
    @parsing = Parsing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @parsing }
    end
  end

  # GET /parsings/1/edit
  def edit
    @parsing = Parsing.find(params[:id])
  end

  # POST /parsings
  # POST /parsings.json
  def create
    @parsing = Parsing.new(params[:parsing])
    respond_to do |format|
      if @parsing.save
        format.html { redirect_to @parsing, notice: 'Parsing was successfully created.' }
        format.json { render json: @parsing, status: :created, location: @parsing }
      else
        format.html { render action: "new" }
        format.json { render json: @parsing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parsings/1
  # PUT /parsings/1.json
  def update
    @parsing = Parsing.find(params[:id])

    respond_to do |format|
      if @parsing.update_attributes(params[:parsing])
        format.html { redirect_to @parsing, notice: 'Parsing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @parsing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parsings/1
  # DELETE /parsings/1.json
  def destroy
    @parsing = Parsing.find(params[:id])
    @parsing.destroy

    respond_to do |format|
      format.html { redirect_to parsings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parsings_helper.rb
module ParsingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parse</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/parsings/_form.html.erb
<%= form_for(@parsing) do |f| %>
  <% if @parsing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parsing.errors.count, "error") %> prohibited this parsing from being saved:</h2>

      <ul>
      <% @parsing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>Номер страницы</p>
    <%= f.text_field :Page %>
  </div>
  <div class="field">
    <p>Название товара</p>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <p>Ссылка на страницу</p>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <p>Количество товаров на странице</p>
    <%= f.text_field :num %>
  </div>
  <div class="actions">
    <%= f.submit "Создать страницу", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/parsings/edit.html.erb
<div class="container">
<h1>Редактирование страницы</h1>
<hr>
<%= render 'form' %>

<%= link_to 'Просмотр', @parsing %> |
<%= link_to 'Назад', parsings_path %>
</div>

app/views/parsings/index.html.erb
<h1>Список страниц</h1>

<table class="table table-bordered">
  <tr>
    <th>Страница</th>
    <th>Название</th>
    <th>Ссылка</th>
    <th>Количество товаров</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parsings.each do |parsing| %>
  <tr>
    <td><%= parsing.Page %></td>
    <td><%= parsing.title %></td>
    <td><%= parsing.link %></td>
    <td><%= parsing.num.to_i %></td>
    <td><%= link_to 'Просмотр', parsing %></td>
    <td><%= link_to 'Редактирование', edit_parsing_path(parsing) %></td>
    <td><%= link_to 'Удалить', parsing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Новая страница', new_parsing_path, class: "btn btn-success" %>

app/views/parsings/new.html.erb
<div class="container">
<h1>Новая страница</h1>
<hr>
<%= render 'form' %>

<%= link_to 'Назад', parsings_path %>
</div>

app/views/parsings/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <b>Страница:</b>
  <%= @parsing.Page %>
</p>

<p>
  <b>Название:</b>
  <%= @parsing.title %>
</p>

<p>
  <b>Ссылка:</b>
  <%= @parsing.link %>
</p>


<p>
  <b>Содержимое страницы:</b>
  <br>
  <%= @string.html_safe%>
</p>


<div class = "span3">
<%= link_to 'Назад', parsings_path, class: "btn btn-danger", style: "float:right" %>
</div>
</div>